---
title: "Data Sources and Literature Review"
author: "Harun Celik"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Data Sources and Literature Review}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## General Introduction

An important objective of the Successful Employment for Persons with Disabilities in Iowa project was its focus on reviewing as many accessible data sources as potentially possible within the time-frame of the DSPG program. The result of this was a survey of data sets that focused on Iowans with disabilities and exploring whether the information contained could be used to provide insight to persons with disabilities and employment in Iowa.

## Datasets Utilized

### American Census Survey (ACS)

Of all the data sources pertaining to persons with a disability (PWD) in Iowa, the ACS includes the most fundamental and complete data set for providing a contextual overview to PWDs. For this reason, this section will document how the ACS data is structured for this particular project.

#### Difficulty Types
In the sections which pertain to disability, the ACS primary collects data on six different kinds of difficulty.


-	Hearing
-	Vision
-	Cognitive
-	Ambulatory
-	Self-care
-	Independent Living 


#### Table Codes and Corresponding Information
On questions of Employment & Income, B18120, B18121, B18140, contain information on: 

-	Employment Status by Disability Status and Type, 
-	Work Experience by Disability Status and Type,
-	Median Earnings by Disability Status by Sex for the Civilian Noninstitutionalized Population with Earnings

On questions of Poverty, B18130, B18131, B21007, B23024 contain information on:

-	Age by Disability Status by Poverty Status
-	Age by Ratio of Income to Poverty Level by Disability Status and Type
-	Age by Veteran Status by Poverty Status by Disability Status for the Civilian Population 18 Years and Over
-	Poverty Status by Disability Status by Employment Status for the Population 20 to 64 Years

On questions of Insurance & Service, B18135, B21100, B22010 contain information on: 

-	Age by Disability Status by Health Insurance Coverage Status
- Service-connected Disability-rating Status and Ratings for Civilian Veterans 18 Years and Over
-	Receipt of Food Stamps/SNAP by Disability Status for Households

On questions regarding General Age and Sex can be found from B18101 – B18107. Additionally on the question of Age, B18108, B26108, B26208 contain information on:

-	 Age by Number of Disabilities
-	Group Quarters Type (3 Types) by Age by Disability Status
-	Group Quarters Type (5 Types) by Age by Disability Status

One Miscellaneous Category is B10052, which contains information on:

-	Disability Status of Grandparents Living with Own Grandchildren by Responsibility for Own Grandchildren and Age of Grandparent


#### Questions in the ACS Questionnaires 

Tables that are outside of the difficulties categories are created using a combination of different questions of the ACS Questionnaires. Employment information for Persons with Disabilities comes from a combination of the Employment, Poverty, Commute, and Disability answers that surveyors respond to when filling the questionnaire.

##### Questions on Disability (Yes/No Questions)

18.	Question Set
a.	Is this person deaf or does he/she have serious difficulty hearing?
b.	Is this person blind or does he/she have serious difficulty seeing even when wearing glasses?


19.	Question Set
a.	Because of a physical, mental, or emotional condition, does this person have serious difficulty concentrating, remembering, or making decisions?
b.	Does this person have serious difficulty walking or climbing stairs?
c.	Does this person have serious difficulty dressing or bathing?


20.	Because of a physical, mental, or emotional condition, does this person have difficulty doing errands alone such as visiting a doctor’s office or shopping?
Questions on Poverty (Fill Value Questions).


43.	Question Set
a.	Wages, salary, commissions, bonuses, or tips from all jobs.
b.	Self-employment income from own nonfarm businesses or farm businesses, including proprietorships and partnerships.
c.	Interest, dividends, net rental income, royalty income, or income from estates and trusts.
d.	Social security or Railroad retirement.
e.	Supplemental Security Income (SSI).
f.	Any public assistance or welfare payments from the state or local welfare offices.
g.	Retirement income, pensions, survivor, or disability income.
h.	Any other sources of income received regularly such as Veteran’s (VA) payments, unemployment compensation, child support, or alimony.


44.	What was this person’s total income during the PAST 12 MONTHS?

### [Behavioral Risk Factor Surveillance System](https://idph.iowa.gov/brfss/Data-by-County)

This data set was used as a comparative supplement to the ACS data set. It contains information matching ACS questionnaires on Disability Status, Age and Type. The geographic scope of this survey is by the county level and the survey is conducted through telephone.

### [Substance Abuse and Mental Health Services Administration (NSDUH)](https://www.datafiles.samhsa.gov/data-sources)

For the purposes of this project, we focused exclusively on the survey questions that related to the Mental Health sections. This information was taken from the _National Survey on Drug Use and Health_ and the geographic scope of this data was by sub-state regions rather than county.

### [Iowa Vocational Rehabilitation Services (IVRS)](https://data.iowa.gov/Vocational-Rehabilitation/Closed-Iowa-Vocational-Rehabilitation-Cases/gcya-t3y9) 

For the assessment of public services, the IVRS data set on Closed Iowa Vocational Rehabilitation Cases was an invaluable resource. This data set had two potential geographic information provided about the clients of the IVRS. The first of these are the office locations that the clients were receiving services from. The second was the location of the client at the end of their services. By calculating the number of employment and the changes in wages for each client, we tried to assess how functional the offices were at helping clients with their employment. 

More information on the IVRS data set can be found in the [Services](https://dspg-2022.github.io/DHR-Disabilities/articles/Dashboard_Development/Services.html) section of the documentation. 

### [Iowa’s Mental Health and Disability Services (MHDS)](https://dhs.iowa.gov/mhds-providers/providers-regions/regions)

For the assessment of public expenditures, we relied on the MDHS regional data sets to learn more about Expenditures, Persons Served, and Unduplicated Persons Served by Service. Due to the way that the data is organized, it took a lot of time to be able to collect all of the MHDS regions into one data table, preventing us from looking at all possible years. The geography of this data set is available for MHDS regions which are not as granular as county data but more so than SAMSHA or IVRS regions.

### [Successful Employment for Blind Iowans by Federal Fiscal Year](https://data.iowa.gov/Vocational-Rehabilitation/Successful-Employment-for-Blind-Iowans-by-Federal-/twt2-zx5z)

Another assessment of public services utilized the Successful Employment for Blind Iowans by Federal Fiscal Year data set from the Iowa Data portal. Unfortunately, the data was last updated for the years of 2016 since 2012, but much like the IVRS data, it contains information regarding hourly wage changes and earnings. The data set does not contain any geographical information.

### Iowa Department of Management – [Budgeted](https://data.iowa.gov/Local-Government-Finance/County-Budgeted-Expenditures-By-Service-Area-By-Fi/gk9s-gz9c) and [Actual](https://data.iowa.gov/Local-Government-Finance/County-Actual-Expenditures-by-Service-Area-by-Fisc/fxbr-vb9c) Expenditures by County on Physical Health and Social Services

For county level expenditures, we focused on data that was provided by the Iowa Department of Management which listed both budgeted and actual expenditures for counties in Iowa. Since they were separate data tables, the process was to first clean and merge them together to later map. We focused on two variables for expenditures; Physical Health and Social Services.

### [Social Security Administration - SSI & OASDI Recipitents, 2020](https://www.ssa.gov/policy/docs/statcomps/ssi_sc/2020/ia.html)

As a public service, this data set provided us with numbers of people and amounts in dollars for all of the people that received OASDI benefits by county. This information is also disaggregated by workers, spouses and children with disabilities or to these respective demographics as a result of someone with a disability in the household. 

## Datasets Unutilized

The following are data sets were reviewed but not utilized due to a number of reasons. Most prominently, data complexity, time-frame of the project, or thematic differences to employment affected our interest and ability to utilize the following data.

## Tier One

`Tier One` data sets are ones that overall matched the thematic interest of the project and would have been investigated further given more available time for the project.

### [Current Population Survey](https://www.census.gov/data/datasets.html)

This data set is based off of the information provided by the Bureau of Labor Statistics and has the ASEC (Annual Social and Economic Supplement) Public Use Data Dictionary containing questions on income and employment for people with disabilities. This data set was not explored due to a lack of time and potential complexities in having to calculate weighted values.


### [Public Use Microdata Sample (PUMS)](https://www.census.gov/programs-surveys/acs/microdata.html)

The PUMS data uses the information collected by the ACS data in order to allow for users to cross-check information that pre-tabulated data products by the ACS don't depict. Due to sample size causing potential reliability errors and a learning curve with the PUMS API, we decided to focus more on the ACS with our limited time.

## Tier Two

These data sets were ones that matched the thematic scope of the project in terms of disability, but did not necessarily contain information on employment, or data accessibility and complexity were a concern. 

### [American Housing Survey (AHS)](https://www.census.gov/programs-surveys/ahs/data/interactive/ahstablecreator.html?s_areas=00000&s_year=2019&s_tablename=TABLE8B&s_bygroup1=1&s_bygroup2=1&s_filtergroup1=1&s_filtergroup2=1)

This data set contains information on households with disabilities by disability type which contains potential for comparison with other sets of information in the ACS. The difficulties with this data set were that the survey information was only gathered for particular areas of states.

### [Survey of Income and Program Participation (SIPP)](https://www.census.gov/programs-surveys/sipp.html)

The SIPP is a nationally representative longitudinal survey that provides information on income, employment, households and government participation programs. The code book for the questionnaires indicates that there are a number of disability related questions. The data set doesn't calculate weights and since this has to be done manually we decided to not utilize the data set for its complexity. 

### [Iowa Department of Administrative Services - Employment Separations](https://data.iowa.gov/Government-Employees/Iowa-Executive-Branch-Voluntary-and-Involuntary-Em/fbgd-5egw)

This data set contains a column of reasons for why employees were separated in the Iowa Executive Branch. One of the possible reasons indicated is Disability and Mental Health. The data set has no particular geographic scope and for lack of priority on other datasets, was not utilized.


### [Iowa Civil Rights Commission - Closed Discrimination Complaint Cases](https://data.iowa.gov/Regulation/Closed-Discrimination-Complaint-Cases-in-Iowa/ha33-u9br) 

This data set contains information on discrimination complaint cases processed by a local agency. Data includes type of closure, dates when case was opened and closed, and basis of complaints received. The clients indicate whether their cases are related to a disability or not. Data doesn't have a geography and no granular information besides the complaints are provided.

### [Medicaid HCBS Aggregate Employment Data](https://iastate.app.box.com/file/982370132843?s=yx3g2g9009kchgsrm3d6d61k2ygtykut)

This Medicaid employment data table covers information from July and October of 2020 as well as April and October of 2021. There is no specific geographic scope for this data set and we were unable to look further into these tables for lack of time.

### [National Health Interview Survey](https://www.cdc.gov/nchs/nhis/2020nhis.htm)

This data set contains detailed questionnaires on health characteristics by demographic and socioeconomic characteristics, including information on people with disabilities. The difficulty in this data set was accessibility and the lack of geographic scope.

### [Bureau of Justice Statistics - Disabilities Reported by Prisoners](https://www.bjs.gov/index.cfm/content/dataonline/content/acf/index.cfm?ty=pbdetail&iid=7306)

This data set contains numbers of federal prisoners in Iowa which are reported to have disabilities disaggregated by similar difficulty types to the ACS data. The data is from 2016 and with limited time for the program, this data set was not utilized for its lack of employment focus for this project.

### [Bureau of Justics Statistics - Crime Against Persons with Disabilities](https://bjs.ojp.gov/library/publications/crime-against-persons-disabilities-2009-2019-statistical-tables)

Contains a data set on Crime Against Persons with Disabilities from the years 2009 to 2019. Since it doesn't contain any information on employment and the geography is at a national level, this data set was not utilized.


### [Bureau of Labor Statistics (BLS)](https://beta.bls.gov/dataQuery/find?st=0&r=20&fq=cg:%5bGeography%5d&fq=cc:%5bCounties+and+Equivalents%5d&more=0&fq=ccd:%5bIowa%5d)

The BLS collects only labor force data at the county level for states. Unfortunately, the information collected by the BLS doesn't include whether a person has disabilities or not. This was why the data was not utilized.

### [Office of Special Education (OSpEd/DoEd)](https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/index.html)

This data set has specific information about children from ages 3 - 21 in need of special education at the state level. Because of its geographic scope at the state level and its data not connecting to employment, we chose to prioritize other data sets.

### [Employment and Training Administration (ETA/US DOL)](https://www.dol.gov/agencies/eta)

Data set was inaccessible until later, this data set was not utilized due to a lack of time.





