---
title: "Harun_Testing"
author: "Xingrui Xue"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)

acs5 <- load_variables(2020, "acs5")
view(acs5)
```

```{r}
DisabledWhite <- c("Under 18 years" = "B18101A_003", "18 to 64 years" = "B18101A_006", "65 years and over" = "B18101A_009")
DisabledBlack <- c("Under 18 years" = "B18101B_003", "18 to 64 years" = "B18101B_006", "65 years and over" = "B18101B_009")
DisabledIndianAlaska <- c("Under 18 years" = "B18101C_003", "18 to 64 years" = "B18101C_006", "65 years and over" = "B18101C_009")
DisabledAsian <- c("Under 18 years" = "B18101D_003", "18 to 64 years" = "B18101D_006", "65 years and over" = "B18101D_009")
DisabledHawaiianPacific <- c("Under 18 years" = "B18101E_003", "18 to 64 years" = "B18101E_006", "65 years and over" = "B18101E_009")
DisabledOtherAlone <- c("Under 18 years" = "B18101F_003", "18 to 64 years" = "B18101F_006", "65 years and over" = "B18101F_009")
DisabledTwoMore <- c("Under 18 years" = "B18101G_003", "18 to 64 years" = "B18101G_006", "65 years and over" = "B18101G_009")
DisabledWhiteAlone <- c("Under 18 years" = "B18101H_003", "18 to 64 years" = "B18101H_006", "65 years and over" = "B18101H_009")
DisabledHispanicLatino <- c("Under 18 years" = "B18101I_003", "18 to 64 years" = "B18101I_006", "65 years and over" = "B18101I_009")
```

```{r}
Disabled <- get_acs(geography = "county",
                   variables = c("WHITE ALONE" = DisabledWhite, "BLACK OR AFRICAN AMERICAN ALONE" = DisabledBlack, "AMERICAN, INDIAN AND ALASKA NATIVE ALONE" = DisabledIndianAlaska, "ASIAN ALONE" = DisabledAsian, "NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE" = DisabledHawaiianPacific, "SOME OTHER RACE ALONE" = DisabledOtherAlone, "TWO OR MORE RACES" = DisabledTwoMore, "WHITE ALONE, NOT HISPANIC OR LATINO" = DisabledWhiteAlone, "HISPANIC OR LATINO" = DisabledHispanicLatino),
                   year = 2020,
                   state = "IA")

Disabled <- Disabled %>% separate(variable, into = c("Race", "Age"), sep = "\\.") %>%
  pivot_wider(names_from = Race, values_from = estimate) %>%
  group_by(NAME, Age)


view(Disabled)
```