---
title: "Employment Status"
output: html_document
date: '2022-06-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(dplyr)
library(ggplot2)
```

```{r}
census_api_key("ab8b0fa7ef0993c579097beb76d0321bce5af443", install = TRUE)
```

```{r}
new_table= read.csv("lookup_county_regions.csv")
View(new_table)
pop_table <- read.csv("Population_by_County.csv")
View(pop_table)
oasdi_table <- read.csv("oasdi_2020.csv")
View(oasdi_table)
oasdi_amount_table <- read.csv("oasdi_amount_2020.csv")
View(oasdi_amount_table)
ssi_table <- read.csv("SSI.csv")
View(ssi_table)
var<-load_variables(2020,"acs5")
View(var)
```

```{r}
colnames(pop_table)[1] <- "County"
```


```{r}
emp_stat_disability <-c("In the Labor Force,Employed with disability"= "C18120_004", "In the Labor force,unemployed with a disability" = "C18120_007",  "Not in the Labor force, with a disability" = "C18120_010")

emp_stat_no_disability <- c("In the Labor Force,Employed with no disability"= "C18120_005", "In the Labor force,unemployed with no disability" = "C18120_008", "Not in the Labor Force, with no disability" = "C18120_011")
```

```{r}
empl_status_disability <- get_acs(
  geography= "county",
  year = 2020,
  variables = emp_stat_disability,
  state= "IA",
  output = "wide"
)
View(empl_status_disability)

#empl_status_disability= empl_status_disability %>% mutate(sum_of_estimates = sum (estimate),overall_perc= 100* (estimate/sum(estimate)) )
#View(empl_status_disability)

empl_status_no_disability <- get_acs(
  geography= "county",
  year = 2020,
  variables = emp_stat_no_disability,
  state= "IA",
  output= "wide"
)
View(empl_status_no_disability)

#empl_status_no_disability= empl_status_no_disability %>% mutate(sum_of_estimates= sum(estimate),overall_perc= 100* (estimate/sum(estimate))) 
#View(empl_status_no_disability)
```

```{r}
#Joining tables
all_emp_stat= full_join(empl_status_disability,empl_status_no_disability)
View(all_emp_stat)

```


```{r}
#Removing MOE
#all_emp_stat = subset(all_emp_stat, select = -c(`In the Labor Force,Employed with disabilityM`, `In the Labor force,unemployed with a disabilityM`, `Not in the Labor force, with a disabilityM`, `In the Labor Force,Employed with no disabilityM`, `In the Labor force,unemployed with no disabilityM`, `Not in the Labor Force, with no disabilityM`) )
```

```{r}
#Finding disability and non disability total
all_emp_stat$disability_total <- (all_emp_stat$`In the Labor Force,Employed with disabilityE`+ all_emp_stat$`Not in the Labor force, with a disabilityE`+ all_emp_stat$`In the Labor force,unemployed with a disabilityE`)
all_emp_stat$no_disability_total <- (all_emp_stat$`In the Labor Force,Employed with no disabilityE`+ all_emp_stat$`In the Labor force,unemployed with no disabilityE`+all_emp_stat$`Not in the Labor Force, with no disabilityE`)
```


```{r}
#Checking if the estimates are reliable based on MOE disabled


CV_employed_disabled = ((all_emp_stat$`In the Labor Force,Employed with disabilityM`/1.645)/all_emp_stat$`In the Labor Force,Employed with disabilityE`)*100

CV_unemployed_disabled = ((all_emp_stat$`In the Labor force,unemployed with a disabilityM`/1.645)/all_emp_stat$`Not in the Labor force, with a disabilityE`)*100

CV_not_in_Labor_force_disabled = ((all_emp_stat$`Not in the Labor force, with a disabilityM`/1.645)/all_emp_stat$`Not in the Labor force, with a disabilityE`)*100

all_emp_stat$CV_employed_disabled = ifelse(CV_employed_disabled > 30 , " low reliability",
                  ifelse(CV_employed_disabled <= 15, "high reliability",
                         "median reliability"))

all_emp_stat$CV_unemployed_disabled = ifelse(CV_unemployed_disabled > 30 , " low reliability",
                  ifelse(CV_unemployed_disabled <= 15, "high reliability",
                         "median reliability"))

all_emp_stat$CV_not_in_Labor_force_disabled = ifelse(CV_not_in_Labor_force_disabled > 30 , " low reliability",
                  ifelse(CV_not_in_Labor_force_disabled <= 15, "high reliability",
                         "median reliability"))

#Checking if the estimates are reliable based on MOE not disabled

CV_employed_not_disabled = ((all_emp_stat$`In the Labor Force,Employed with no disabilityM`/1.645)/all_emp_stat$`In the Labor Force,Employed with no disabilityE`)*100

CV_unemployed_not_disabled = ((all_emp_stat$`In the Labor force,unemployed with no disabilityM`/1.645)/all_emp_stat$`In the Labor force,unemployed with no disabilityE`)*100

CV_not_in_Labor_force_not_disabled = ((all_emp_stat$`Not in the Labor Force, with no disabilityM`/1.645)/all_emp_stat$`Not in the Labor Force, with no disabilityE`)*100

all_emp_stat$CV_employed_not_disabled = ifelse(CV_employed_not_disabled > 30 , " low reliability",
                  ifelse(CV_employed_not_disabled <= 15, "high reliability",
                         "median reliability"))

all_emp_stat$CV_unemployed_not_disabled = ifelse(CV_unemployed_not_disabled > 30 , " low reliability",
                  ifelse(CV_unemployed_not_disabled <= 15, "high reliability",
                         "median reliability"))

all_emp_stat$CV_not_in_Labor_force_not_disabled = ifelse(CV_not_in_Labor_force_not_disabled > 30 , " low reliability",
                  ifelse(CV_not_in_Labor_force_not_disabled <= 15, "high reliability",
                         "median reliability"))

View(all_emp_stat)
```

```{r}
#Finding percentage gap

all_emp_stat = all_emp_stat %>% mutate(percent_in_labor_force_employed_disabled = 100 * (all_emp_stat$`In the Labor Force,Employed with disabilityE`/all_emp_stat$disability_total),
percent_in_labor_force_employed_not_disabled = 100 * (all_emp_stat$`In the Labor Force,Employed with no disabilityE`/all_emp_stat$no_disability_total), percent_in_labor_force_unemployed_disabled = 100 * (all_emp_stat$`In the Labor force,unemployed with a disabilityE`/all_emp_stat$disability_total),
percent_in_labor_force_unemployed_not_disabled = 100 * (all_emp_stat$`In the Labor force,unemployed with no disabilityE`/all_emp_stat$no_disability_total), 
percent_not_in_labor_force_disabled = 100 * (all_emp_stat$`Not in the Labor force, with a disabilityE`/all_emp_stat$disability_total),
percent_not_in_labor_force_not_disabled = 100 * (all_emp_stat$`Not in the Labor Force, with no disabilityE`/all_emp_stat$no_disability_total))


all_emp_stat = all_emp_stat %>% mutate(percent_in_labor_force_employed_gap = percent_in_labor_force_employed_not_disabled - percent_in_labor_force_employed_disabled, percent_in_labor_force_unemployed_gap = percent_in_labor_force_unemployed_not_disabled - percent_in_labor_force_unemployed_disabled , percent_not_in_labor_force_gap =    percent_not_in_labor_force_not_disabled - percent_not_in_labor_force_disabled )
View(all_emp_stat)
```

```{r}
#State Avg Employed Not Disabled
max(all_emp_stat$percent_in_labor_force_employed_not_disabled)
state_avg=mean(all_emp_stat$percent_in_labor_force_employed_not_disabled)
min(all_emp_stat$percent_in_labor_force_employed_not_disabled)

all_emp_stat$compared_to_state_avg_end= ifelse( all_emp_stat$percent_in_labor_force_employed_not_disabled > state_avg , "above average",
                  ifelse(all_emp_stat$percent_in_labor_force_employed_not_disabled < state_avg, "below average",
                         "average"))


#State Avg Employed Disabled
max(all_emp_stat$percent_in_labor_force_employed_disabled)
state_avg2=mean(all_emp_stat$percent_in_labor_force_employed_disabled)
min(all_emp_stat$percent_in_labor_force_employed_disabled)

all_emp_stat$compared_to_state_avg_ed= ifelse( all_emp_stat$percent_in_labor_force_employed_disabled > state_avg2 , "above average",
                  ifelse(all_emp_stat$percent_in_labor_force_employed_disabled < state_avg2, "below average",
                         "average"))

#State Avg Unemployed Disabled
max(all_emp_stat$percent_in_labor_force_unemployed_disabled)
state_avg3=mean(all_emp_stat$percent_in_labor_force_unemployed_disabled)
min(all_emp_stat$percent_in_labor_force_unemployed_disabled)

all_emp_stat$compared_to_state_avg_ud= ifelse(all_emp_stat$percent_in_labor_force_unemployed_disabled > state_avg3 , "above average",
                  ifelse(all_emp_stat$percent_in_labor_force_unemployed_disabled < state_avg3, "below average",
                         "average"))

#State Avg Not in Lab force disabled
max(all_emp_stat$percent_not_in_labor_force_disabled)
state_avg4=mean(all_emp_stat$percent_not_in_labor_force_disabled)
min(all_emp_stat$percent_not_in_labor_force_disabled)

all_emp_stat$compared_to_state_avg_nd = ifelse(all_emp_stat$percent_not_in_labor_force_disabled > state_avg4 , "above average",
                  ifelse(all_emp_stat$percent_not_in_labor_force_disabled < state_avg4, "below average",
                         "average"))
View(all_emp_stat)
```


```{r}
colnames(all_emp_stat)[2] <-"County"
colnames(all_emp_stat)[3] <- "In the Labor Force, Employed with Disability (Estimate)"
colnames(all_emp_stat)[4] <- "In the Labor Force, Employed with Disability (MOE)"
colnames(all_emp_stat)[5] <- "In the Labor Force, Unemployed with Disability (Estimate)"
colnames(all_emp_stat)[6] <- "In the Labor Force, Unemployed with Disability (MOE)"
colnames(all_emp_stat)[7] <- "Not in the Labor Force, with Disability (Estimate)"
colnames(all_emp_stat)[8] <- "Not in the Labor Force, with Disability (MOE)"
colnames(all_emp_stat)[9] <- "In the Labor Force, Employed with NO Disability (Estimate)"
colnames(all_emp_stat)[10] <- "In the Labor Force, Employed with NO Disability (MOE)"
colnames(all_emp_stat)[11] <- "In the Labor Force, Unemployed with NO Disability (Estimate)"
colnames(all_emp_stat)[12] <- "In the Labor Force, Unemployed with NO Disability (MOE)"
colnames(all_emp_stat)[13] <- "Not in the Labor Force, with NO Disability (Estimate)"
colnames(all_emp_stat)[14] <- "Not in the Labor Force, with NO Disability (MOE)"
```


```{r}
all_emp_stat$County<-gsub("County, Iowa","",as.character(all_emp_stat$County))
```

```{r}
#Joining table to Metropolitan table
new_all_emp_stat = merge(x = all_emp_stat, y = new_table, by = "GEOID", all.x = TRUE)
View(new_all_emp_stat)
```

```{r}
merged_pop_table = merge(x = all_emp_stat, y = pop_table, by = "GEOID", all.x = TRUE)
View(merged_pop_table)
```

```{r}
#Merging OASDI Table (Number and Amount)
merged_oasdi_table = merge(x = all_emp_stat, y = oasdi_table, by = "GEOID", all.x = TRUE)
View(merged_oasdi_table)

merged_oasdi_amount_table = merge(x = all_emp_stat, y = oasdi_amount_table, by = "GEOID", all.x = TRUE)
View(merged_oasdi_amount_table)
```

```{r}
merged_ssi_table = merge(x = all_emp_stat, y = ssi_table, by = "GEOID", all.x = TRUE)
View(merged_ssi_table)
```


```{r}
#Converting into a csv 
write.csv(all_emp_stat, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Labor_Force_gaps_county-level.csv", row.names = FALSE)
write.csv(new_all_emp_stat, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Merged_table_county-level.csv", row.names = FALSE)
write.csv(merged_pop_table, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Merged_table_pop_county_level.csv", row.names = FALSE)

write.csv(merged_oasdi_table, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Merged_OASDI_table.csv", row.names = FALSE)

write.csv(merged_oasdi_amount_table, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Merged_OASDI_amount_table.csv", row.names = FALSE)

write.csv(merged_ssi_table, "S:/misc/clg/DSPG2022/ProjectA/Sanika-Merged_SSI_table.csv", row.names = FALSE)
```
