---
title: "Xingrui_ACS5_AgeRace"
author: "Xingrui Xue"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)

acs5 <- load_variables(2020, "acs5")
view(acs5)
```

```{r}
DisabledWhite <- c("Under 18 years" = "B18101A_003", "18 to 64 years" = "B18101A_006", "65 years and over" = "B18101A_009")
DisabledBlack <- c("Under 18 years" = "B18101B_003", "18 to 64 years" = "B18101B_006", "65 years and over" = "B18101B_009")
DisabledIndianAlaska <- c("Under 18 years" = "B18101C_003", "18 to 64 years" = "B18101C_006", "65 years and over" = "B18101C_009")
DisabledAsian <- c("Under 18 years" = "B18101D_003", "18 to 64 years" = "B18101D_006", "65 years and over" = "B18101D_009")
DisabledHawaiianPacific <- c("Under 18 years" = "B18101E_003", "18 to 64 years" = "B18101E_006", "65 years and over" = "B18101E_009")
DisabledOtherAlone <- c("Under 18 years" = "B18101F_003", "18 to 64 years" = "B18101F_006", "65 years and over" = "B18101F_009")
DisabledTwoMore <- c("Under 18 years" = "B18101G_003", "18 to 64 years" = "B18101G_006", "65 years and over" = "B18101G_009")
DisabledWhiteAlone <- c("Under 18 years" = "B18101H_003", "18 to 64 years" = "B18101H_006", "65 years and over" = "B18101H_009")
DisabledHispanicLatino <- c("Under 18 years" = "B18101I_003", "18 to 64 years" = "B18101I_006", "65 years and over" = "B18101I_009")
```

```{r}
White <- get_acs(geography = "county",
                           variables = DisabledWhite,
                           year = 2020,
                           state = "IA")
White <- White %>% group_by(NAME) %>%
  mutate(Percentage = estimate / sum(estimate) * 100)

View(White)
```