---
title: "Joel_IVRS_Script"
author: "Harun"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(ggplot2)
library(dplyr)

# Read in data
IVRS <- read.csv("Data/Closed_Iowa_Vocational_Rehabilitation_Cases.csv")

```

## Number of Cases each Year

```{r Number of Cases each Year, echo=FALSE}
yearly.cases <- IVRS %>%
  count(Federal.Fiscal.Year, name = "Total.Cases") %>%
  group_by(Federal.Fiscal.Year)
  

ggplot(data = yearly.cases, aes(x = Federal.Fiscal.Year, y = Total.Cases)) +
  geom_bar(fill = "orange", stat = "identity") +
  xlab("Year") +
  ylab("Number of Cases")
```

## Cases by Client County

```{r Cases by Client County, echo=FALSE}
county.cases <- IVRS %>%
  count(Client.County, name = "Total.Cases") %>%
  group_by(Client.County)
  

ggplot(data = county.cases, aes(x = Client.County, y = Total.Cases)) +
  geom_bar(fill = "orange", stat = "identity") +
  xlab("County") +
  ylab("Number of Cases") +
  theme(axis.text.x = element_text(angle = 90))
```

(Unhelpful visually, to many counties)

Sorted table shows counties with highest number of cases.

```{r}
county.cases %>% arrange(desc(Total.Cases))
```


# Cases by Office Area
```{r Number of Cases each Year, echo=FALSE}
office.cases <- IVRS %>%
  count(Office.Area, name = "Total.Cases") %>%
  group_by(Office.Area)
  

ggplot(data = office.cases, aes(x = Office.Area, y = Total.Cases)) +
  geom_bar(fill = "orange", stat = "identity") +
  xlab("Office") +
  ylab("Number of Cases") +
  theme(axis.text.x = element_text(angle = 45))
```


