---
title: "Sanika_PUMS_Script"
author: "Harun"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
pums_var_2020 <- pums_variables %>% filter(year == 2019, survey == "acs1")
View(pums_var_2020)



pums_var_2020 <- pums_variables %>% filter(year == 2020, survey == "acs5")
View(pums_var_2020)

x = insurance_65_above = "HINS3"

y = insurance_low_income= "HINS4"

vt_pums <- get_pums(
  variables = x,
  state = "IA",
  survey = "acs5",
  year = 2020
  )
View(vt_pums)

vt_pums_new <- pums_var_2020 %>% filter(val_label== c("Civilian employed, at work", "Unemployed"))
View(vt_pums_new)

#comparing medicaid income for disabled people of age 65+ vs low income people
ggplot(vt_pums, aes(x))+
  geom_histogram()+
  labs(x= "Insurance",
       y= "pop")
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
