---
title: "Xingrui_ACS5_Script"
author: "Xingrui"
date: '2022-06-08'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)
library(sf)

var <- load_variables(2020, "acs5")
```

```{r}
MaleAge <- c("Under 5 years" = "B18101_004", "5 to 17 years" = "B18101_007", "18 to 34 years" = "B18101_010", "35 to 64 years" = "B18101_013", "65 to 74 years" = "B18101_016", "75 years and over" = "B18101_019")
FemaleAge <- c("Under 5 years" = "B18101_023", "5 to 17 years" = "B18101_026", "18 to 34 years" = "B18101_029", "35 to 64 years" = "B18101_032", "65 to 74 years" = "B18101_035", "75 years and over" = "B18101_038")

AgeMale <- get_acs(geography = "state",
        variables = MaleAge,
        year = 2020,
        state = "IA")
AgeMale$sex <- "Male"

AgeFemale <- get_acs(geography = "state",
        variables = FemaleAge,
        year = 2020,
        state = "IA")
AgeFemale$sex <- "Female"

Age <- full_join(AgeMale, AgeFemale)

Age %>% mutate(population = ifelse(sex == "Male", estimate * -1, estimate * 1)) %>%
  ggplot(aes(x = variable,
             y = population,
             fill = sex)) +
  coord_flip() +
  geom_bar(stat = "identity") +
  labs(title = "Age of Persons With Disabilities by Sex",
       subtitle = "2016 - 2020 American Community Survey",
       x = "Age",
       y = "Absolute Value of Population by Sex")
```

```{r}
race <- data.frame(Race = c("White alone", "Black or African American alone", "American Indian and Alaska Native alone", "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some other race alone", "Two or more races", "White alone, not Hispanic or Latino", "Hispanic or Latino (of any race)"),
          Percent = c(12.1, 10.0, 16.8, 5.7, 9.9, 7.7, 10.1, 12.4, 7.3))

ggplot(race, aes(x = "", y = Percent, fill = Race)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start = 0) +
  labs(title = "Percentage of the Population With Disabilities by Race",
       subtitle = "2016 - 2020 American Community Survey") +
  geom_text(aes(label = paste0(Percent, "%")),
            position = position_stack(vjust = 0.5)) +
  theme_void()
```
```{r}
difficultyMale <- c(Vision = "B18103_002", "Self-care" = "B18106_002", "Independent living" = "B18107_002", Hearing = "B18102_002", Cognitive = "B18104_002", Ambulatory = "B18105_002")

difficultyFemale <- c(Vision = "B18103_021", "Self-care" = "B18106_018", "Independent living" = "B18107_015", Hearing = "B18102_021", Cognitive = "B18104_018", Ambulatory = "B18105_018")

Difficulty <- get_acs(geography = "state",
                      variables = c(Male = difficultyMale,
                                    Female = difficultyFemale),
                      year = 2020,
                      state = "IA")

Difficulty$Sex <- rep(c("Male", "Female"), 6)

ggplot(Difficulty, aes(x = variable, y = estimate, fill = Sex)) +
  geom_bar(position="stack", stat="identity") +
  labs(title = "Disabled Population by Type of Disability",
       subtitle = "2016 - 2020 American Community Survey") +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
EMPLOYMENT <- c(Employed = "C18120_004", Unemployed = "C18120_007")

Employment <- get_acs(geography = "state",
        variables = EMPLOYMENT,
        year = 2020,
        state = "IA")

ggplot(Employment, aes(variable, weight = estimate)) +
  geom_bar() +
  labs(x = "Employment Status",
       y = "Population",
       title = "Disabled Population in the Labor Force by Employment Status",
       subtitle = "2016 - 2020 American Community Survey") +
  geom_errorbar(aes(ymin = estimate - moe,
                    ymax = estimate + moe,
                    width = 0.5,
                    color = "Margin of Error")) +
  geom_text(aes(y = estimate,
                label = estimate,
                vjust = 2,
                color = "ACS Estimate"))
```

```{r}
Employed <- get_acs(geography = "county",
                    variables = "C18120_004",
                    year = 2020,
                    state = "IA",
                    geometry = TRUE)

Unemployed <- get_acs(geography = "county",
                    variables = "C18120_007",
                    year = 2020,
                    state = "IA",
                    geometry = TRUE)

Employment1 <- st_intersection(Employed, Unemployed)

Employment1$percentage <- Employment1$estimate / (Employment1$estimate + Employment1$estimate.1) * 100

ggplot(Employment1, aes(fill = percentage)) +
  geom_sf()  +
  theme_minimal() +
  coord_sf(datum = NA) +
  scale_fill_continuous(type = "viridis", direction = -1) +
  labs(title = "Employment Rate of Persons With Disabilities in the Labor Force",
       subtitle = "2016 - 2020 American Community Survey")
```

```{r}
Sex <- c("Disabled Male" = "B18140_003", "Disabled Female" = "B18140_004",
         "Nondisabled Male" = "B18140_006", "Nondisabled Female" = "B18140_007")

MedEarningBySex <- get_acs(geography = "state",
        variables = Sex,
        year = 2020,
        state = "IA")

MedEarningBySex$sex <- rep(c("Male", "Female"), 2)

ggplot(MedEarningBySex, aes(x = sex, y = estimate, fill = variable)) +
  geom_bar(position="dodge", stat="identity") +
  labs(title = "Median Earning by Sex and Disability Status",
       subtitle = "2016 - 2020 American Community Survey",
       x = "Sex by Disability Status",
       y = "Median Earnings")
```

```{r}
ratio <- c("Under .50" = "C18131_003", ".50 to .99" = "C18131_006")

Ratio <- get_acs(geography = "county",
                 variables = ratio,
                 year = 2020,
                 state = "IA")

Ratio <- aggregate(estimate ~ NAME, data = Ratio, FUN = sum)

AgeMale <- get_acs(geography = "county",
        variables = MaleAge,
        year = 2020,
        state = "IA")

AgeFemale <- get_acs(geography = "county",
        variables = FemaleAge,
        year = 2020,
        state = "IA")

Age <- full_join(AgeMale, AgeFemale)

OverallPop <- aggregate(estimate ~ NAME, data = Age, FUN = sum)

Employment1$Proportion <- Ratio$estimate / OverallPop$estimate

ggplot(Employment1, aes(fill = Proportion)) +
  geom_sf()  +
  theme_minimal() +
  coord_sf(datum = NA) +
  scale_fill_continuous(type = "viridis") +
  labs(title = "Proportion of the Population Living in Poverty Among All Disabled People",
       subtitle = "2016 - 2020 American Community Survey")
```


```{r}
WorkExperience <- c("Full-time" = "C18121_003", "Less than full-time" = "C18121_006", "Did not work" = "C18121_009")

experience <- get_acs(geography = "county",
        variables = WorkExperience,
        year = 2020,
        state = "IA")

experience
```